project:
  type: website
  output-dir: ../../docs/blog

website:
  title: "Medhat Omr"
  navbar:
    title: false
    background: dark
    pinned: true
    collapse: false
    left:
      #  ğŸ  ğŸ“® ğŸ‘¨ğŸ½â€ğŸ’» ğŸ ğŸ¤ ğŸ“š
      - text: "Blog"
        href: index.qmd
    # - text: Notes
    #   file: notes/index.qmd
    # - text: Hire Me
    #   href: https://parlance-labs.com/
    # - text: OSS
    #   file: oss/opensource.qmd
    # - text: Teaching
    #   file: talks.qmd
    #   target: _blank

format:
  html:
    respect-user-color-scheme: true
    theme:
      dark:
        - darkly
        - brand
      light:
        - flatly # builtâ€‘in BS theme
        - brand # â† magically expands to _brand.yml
    css: styles.css
